package org.redacted.Commands.Fun;

import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import org.redacted.Commands.Category;
import org.redacted.Commands.Command;
import org.redacted.Redacted;
import org.redacted.util.embeds.EmbedUtils;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

/**
 * Command that generates a funny inspiring quote.
 * Uses the InspiroBot API.
 *
 * @author Derrick Eberlein
 */
public class InspireCommand extends Command {

    public InspireCommand(Redacted bot) {
        super(bot);
        this.name = "inspire";
        this.description = "Display an inspirational quote generated by an AI.";
        this.category = Category.FUN;
    }

    @Override
    public void execute(SlashCommandInteractionEvent event) {
        try {
            // Create HttpClient instance
            HttpClient client = HttpClient.newHttpClient();

            // Build the request
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create("https://inspirobot.me/api?generate=true"))
                    .build();

            // Send the request and get the response
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            // Get the picture URL from the response
            String pictureUrl = response.body();

            // Reply with the picture URL
            event.reply(pictureUrl).queue();
        } catch (IOException | InterruptedException e) {
            String text = "I was unable to fetch an inspiring quote!";
            event.replyEmbeds(EmbedUtils.createError(text)).queue();
        }
    }
}
